import { type NextPage } from "next";
import Head from "next/head";
import LoginButton from "~/components/LoginButton";
import TitleAndDescLink from "~/components/TitleAndDescLink";
import TopNav from "~/components/TopNav";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from me" });

  return (
    <>
      <Head>
        <title>Bored</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen flex min-h-screen w-screen flex-col items-center justify-center bg-[#ffe5ec]">
        <TopNav />
        <div className="h-ful m-0 flex grow-[1] flex-wrap items-end justify-center bg-[#ffe5ec] py-5 text-center">
          <h1 className="h-full text-8xl font-extrabold tracking-tight text-[#590d22]">
            I am <span className="text-[#ff4d6d]">Bored</span>
          </h1>
        </div>
        <div className="flex h-full grow-[1] flex-col items-center justify-start gap-11 bg-gradient-to-b from-[#ffe5ec] to-[#ffe5ec] py-5 pt-10">
          <div className="grid  grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <TitleAndDescLink
              title="Hello"
              text="I am bored today, so I am creating a website!"
              url=""
            />
            <TitleAndDescLink title="Bored" text="Well, what to make?" url="" />
          </div>
          <div className="flex flex-col items-center justify-center gap-2">
            <p className="text-2xl text-[#590d22]">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
