import { type NextPage } from "next";
import Head from "next/head";
import BottomNav from "~/components/BottomNav";
import TitleAndDescLink from "~/components/TitleAndDescLink";
import TopNav from "~/components/TopNav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bored.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen flex min-h-screen w-screen flex-col items-center justify-start bg-pink-100">
        <TopNav />
        <div className="m-0 flex grow-[1] flex-wrap items-end justify-center bg-pink-100 py-5 text-center">
          <h1 className="h-full text-8xl font-extrabold tracking-tight text-maroon">
            I am <span className="text-pink-200">Bored</span>.
          </h1>
        </div>
        <div className="flex h-full grow-[2] flex-col items-center justify-start gap-11 bg-pink-100 py-5 pt-10">
          <div className="grid  grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <TitleAndDescLink
              title="Hello"
              text="I am bored today, so I am creating a website!"
              url=""
            />
            <TitleAndDescLink title="Bored" text="Well, what to make?" url="" />
          </div>
        </div>
        <BottomNav />
      </main>
    </>
  );
};

export default Home;
